// <auto-generated />
using DotNetMessagingApplication.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetMessagingApplication.Server.Migrations
{
    [DbContext(typeof(MessagingAppContext))]
    [Migration("20250817132213_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Friendship", b =>
                {
                    b.Property<int>("FollowsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowsId", "FollowedById");

                    b.HasIndex("FollowedById");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Friendship", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "FollowedBy")
                        .WithMany("Following")
                        .HasForeignKey("FollowedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "Follows")
                        .WithMany("Followers")
                        .HasForeignKey("FollowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedBy");

                    b.Navigation("Follows");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.User", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");
                });
#pragma warning restore 612, 618
        }
    }
}
