// <auto-generated />
using System;
using DotNetMessagingApplication.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetMessagingApplication.Server.Migrations
{
    [DbContext(typeof(MessagingAppContext))]
    partial class MessagingAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("Chat", (string)null);

                    b.HasDiscriminator().HasValue("Chat");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.GroupChatMember", b =>
                {
                    b.Property<int>("GroupChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupChatMember", (string)null);
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeSent")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("RecipientChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Reaction", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Relationship", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OtherPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "OtherPersonId");

                    b.HasIndex("OtherPersonId");

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendEmailNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("TimeLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsId", "UserId");

                    b.HasIndex("SettingsId")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronouns")
                        .HasColumnType("TEXT");

                    b.Property<int>("SettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.DirectMessage", b =>
                {
                    b.HasBaseType("DotNetMessagingApplication.Server.Data.Models.Chat");

                    b.Property<int>("OtherPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("OtherPersonId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("DirectMessage");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.GroupChat", b =>
                {
                    b.HasBaseType("DotNetMessagingApplication.Server.Data.Models.Chat");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("AdminId");

                    b.HasDiscriminator().HasValue("GroupChat");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Child", b =>
                {
                    b.HasBaseType("DotNetMessagingApplication.Server.Data.Models.User");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("Child");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.GroupChatMember", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.GroupChat", "GroupChat")
                        .WithMany("Members")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "User")
                        .WithMany("GroupChatMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Message", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.Chat", "RecipientChat")
                        .WithMany("Messages")
                        .HasForeignKey("RecipientChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("RecipientChat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Reaction", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "User")
                        .WithMany("ReactionsGiven")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Relationship", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "OtherPerson")
                        .WithMany("Followers")
                        .HasForeignKey("OtherPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "User")
                        .WithMany("Following")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OtherPerson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Settings", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("DotNetMessagingApplication.Server.Data.Models.Settings", "SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.DirectMessage", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "OtherPerson")
                        .WithMany("DirectMessageAsOtherPerson")
                        .HasForeignKey("OtherPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "User")
                        .WithMany("DirectMessageAsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtherPerson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.GroupChat", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "Admin")
                        .WithMany("GroupChatAdminOf")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Child", b =>
                {
                    b.HasOne("DotNetMessagingApplication.Server.Data.Models.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.User", b =>
                {
                    b.Navigation("DirectMessageAsOtherPerson");

                    b.Navigation("DirectMessageAsUser");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("GroupChatAdminOf");

                    b.Navigation("GroupChatMemberships");

                    b.Navigation("MessagesSent");

                    b.Navigation("ReactionsGiven");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetMessagingApplication.Server.Data.Models.GroupChat", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
